web/router.ex
defmodule Wubytex.Router do
  use Wubytex.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Wubytex do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Wubytex do
  #   pipe_through :api
  # end

  scope "/auth", Wubytex do
    pipe_through :browser

    # get "/:provider", AuthController, :request
    # get "/:provider/callback", AuthController, :callback
    # post "/identity/callback", AuthController, :identity_callback
    post "/signup", AuthController, :sign_up
    post "/signin", AuthController, :sign_in
    post "/signout", AuthController, :sign_out
  end

  # scope "/auth", Wubytex do
  #   pipe_through :browser

  #   # get "/:provider", AuthController, :request
  #   # get "/:provider/callback", AuthController, :callback
  #   post "/identity/callback", AuthController, :identity_callback
  # end
end

lib/wubytex/endpoint.ex
defmodule Wubytex.Endpoint do
  use Phoenix.Endpoint, otp_app: :wubytex

  socket "/socket", Wubytex.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :wubytex, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_wubytex_key",
    signing_salt: "Dz1xGNdU"

  plug Wubytex.Router
end

lib/wubytex/repo.ex
defmodule Wubytex.Repo do
  use Ecto.Repo, otp_app: :wubytex
end

web/controllers/auth_controller.ex
defmodule Wubytex.AuthController do
  use Wubytex.Web, :controller
  plug Ueberauth #, providers: [:identity], base_path: "/auth"

  def sign_in(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    case validate_password(auth) do
      :ok ->
        user = %{id: auth.uid, username: auth.extra.raw_info["username"]}
        conn
        |> put_flash(:info, "Successfully authenticated.")
        |> put_session(:current_user, user)
        |> redirect(to: "/")
      { :error, reason } ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end

  def sign_up(conn, params) do
    conn |> put_flash(:info, "sign up") |> redirect(to: "/")
  end

  def sign_out(conn, _params) do
    conn
    |> put_flash(:error, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end

  def validate_password(auth) do
    :ok
    # {:error, "#{inspect(auth)}"}
  end
end

web/controllers/page_controller.ex
defmodule Wubytex.PageController do
  use Wubytex.Web, :controller

  alias Ueberauth.Strategy.Helpers

  def index(conn, _params) do
    render conn, "index.html", callback_url: Helpers.callback_url(conn),
                               current_user: get_session(conn, :current_user)
  end
end

web/views/error_view.ex
defmodule Wubytex.ErrorView do
  use Wubytex.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Wubytex.LayoutView do
  use Wubytex.Web, :view
end

web/views/page_view.ex
defmodule Wubytex.PageView do
  use Wubytex.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Wubytex!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<!--
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
    </ul>
  </div>
</div>
-->

<%= if @current_user do %>
  <%= inspect(@callback_url) %>
  <pre><%= inspect @current_user %></pre>

  <h2>Welcome, <%= @current_user.username %>!</h2>
  <img src="<%=# @current_user.avatar %>" class="img-circle"/>
  <img src="https://avatars.io/twitter/weapp" class="img-circle" style="height:50px"/>
  <%=# link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %>
  <br>

<%= form_tag "/auth/signout", method: "post" do %>
  <div class='control-group'>
    <button class='btn btn-danger'>Sign Out</button>
  </div>
<% end %>

<% else %>


<div class="row marketing">
  <div class="col-lg-6">
    <h4>Sign up</h4>
    <%= form_tag "/auth/signup", method: "post" do %>
      <div class='control-group'>
        <label class='control-label' for='nickname-input'>Username</label>
        <input class='form-control' type='text' name='username' value='<%= @conn.params["username"] %>' />
      </div>

      <div class='control-group'>
        <label class='control-label' for='password-input'>Password</label>
        <input class='form-control' type='password' name='password' />
      </div>

      <div class='control-group'>
        <label class='control-label' for='password-confirmation-input'>Confirm Password</label>
        <input class='form-control' type='password' name='password_confirmation' />
      </div>

      <div class='control-group'>
        <button class='btn btn-primary'>Sign Up</button>
      </div>
    <% end %>
  </div>

  <div class="col-lg-6">
    <h4>Sign in</h4>
    <%= form_tag "/auth/signin", method: "post" do %>
      <div class='control-group'>
        <label class='control-label' for='nickname-input'>Username</label>
        <input class='form-control' type='text' name='username' value='<%= @conn.params["username"] %>' />
      </div>

      <div class='control-group'>
        <label class='control-label' for='password-input'>Password</label>
        <input class='form-control' type='password' name='password' />
      </div>

      <div class='control-group'>
        <button class='btn btn-primary'>Sign In</button>
      </div>
    <% end %>
  </div>
</div>

<% end %>